networks:
  demo:
    driver: bridge

services:

  pyroscope:
    image: grafana/pyroscope:1.10.0
    container_name: pyroscope
    restart: always
    ports:
      - 4040:4040
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - demo

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    environment:
      TZ: Europe/Lisbon
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true # Allow anonymous access
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin # Set the role for anonymous users to Admin
      GF_AUTH_BASIC_ENABLED: false # Disable basic auth
      GF_FEATURE_TOGGLES_ENABLE: flameGraph,traceqlEditor # Enable flameGraph for Pyroscope / traceqlEditor for Tempo
      GF_INSTALL_PLUGINS: https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app,grafana-pyroscope-app # Install Loki Explore plugin and Pyroscope plugin
    ports:
      - 3000:3000
    volumes:
      - ./src/Grafana/grafana.ini:/etc/grafana/grafana.ini # Config
      - ./src/Grafana/data-source.yml:/etc/grafana/provisioning/datasources/data-source.yml # Data source configurations
      # - ./src/Grafana/dashboards:/etc/grafana/provisioning/dashboards # Folder containing dashboards
      - ./src/Grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml # Dashboard configurations
    networks:
      - demo
    depends_on:
      pyroscope:
        condition: service_started


  api:
    build:
      context: .
      dockerfile: ./src/Demo.Api/Dockerfile
    image: technobre/demo-api
    container_name: api-users
    restart: always
    environment:
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
    ports:
      - 8080:8080
    networks:
      - demo
    depends_on:
      pyroscope:
        condition: service_started
